load('../revolver copy master 12 otto/data_old/CRC.RData')
CRC

require(tidyverse)
require(revolver)

CROSS_CRC_ADENOCARCINOMA = CRC %>% as_tibble %>% mutate(cluster = paste(cluster))

CROSS_CRC_ADENOCARCINOMA_REVOLVER = revolver_cohort(CROSS_CRC_ADENOCARCINOMA, MIN.CLUSTER.SIZE = 0)

non_recurrent = Stats_drivers(CROSS_CRC_ADENOCARCINOMA_REVOLVER) %>% 
  filter(N_tot == 1) %>% 
  pull(variantID)

CROSS_CRC_ADENOCARCINOMA_REVOLVER = remove_drivers(CROSS_CRC_ADENOCARCINOMA_REVOLVER, non_recurrent)

CROSS_CRC_ADENOCARCINOMA_REVOLVER = compute_mutation_trees(CROSS_CRC_ADENOCARCINOMA_REVOLVER)

CROSS_CRC_ADENOCARCINOMA_REVOLVER = revolver_fit(CROSS_CRC_ADENOCARCINOMA_REVOLVER, parallel = F, n = 5)

CROSS_CRC_ADENOCARCINOMA_REVOLVER = revolver_cluster(CROSS_CRC_ADENOCARCINOMA_REVOLVER)

CROSS_CRC_ADENOCARCINOMA_REVOLVER = revolver_jackknife(CROSS_CRC_ADENOCARCINOMA_REVOLVER, resamples = 5)

plot_clusters(CROSS_CRC_ADENOCARCINOMA_REVOLVER, cutoff_trajectories = 1, cutoff_drivers = 0)
plot_drivers_graph(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_dendrogram(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_DET_index(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_drivers_clonality(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_drivers_occurrence(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_jackknife_cluster_stability(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_jackknife_coclustering(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_jackknife_trajectories_stability(CROSS_CRC_ADENOCARCINOMA_REVOLVER)
plot_patient_trees(CROSS_CRC_ADENOCARCINOMA_REVOLVER, CROSS_CRC_ADENOCARCINOMA_REVOLVER$patients[1])
